repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit

  # Black (code formatting)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Ruff (linting + import sorting + fixes)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format